FROM p4lang/p4runtime-sh:latest

SHELL ["/bin/bash", "-c"]

WORKDIR /p4runtime-sh/

ENV PKG_DEPS git

# git is required for codecov
RUN apt-get update && \
    apt-get install -y --no-install-recommends $PKG_DEPS && \
    rm -rf /var/cache/apt/* /var/lib/apt/lists/* && \
    echo 'source venv/bin/activate' > /p4runtime-sh/activate

COPY ./shell.py /p4runtime-sh/p4runtime_sh/shell.py

RUN source $VENV/bin/activate && \
    pip3 install -r requirements-dev.txt && \
    rm -rf ~/.cache/pip

ENTRYPOINT []
